version: '3.7'

services:
  db:
    container_name: db-postgres
    image: postgres:11.2-alpine
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poc
    ports:
      - 30001:5432
    networks:
      - mynetworks
  nestpoc:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: npm run start:dev
    container_name: nestpoc
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - mynetworks
    restart: unless-stopped
    ports:
      - 3000:3000
networks:
  mynetworks:
